// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWbL6rARwuMqlhF88hTGEF_UFLPrUOW8',
    appId: '1:439452598995:web:87864905a4723ffd0aca26',
    messagingSenderId: '439452598995',
    projectId: 'auth-88e83',
    authDomain: 'auth-88e83.firebaseapp.com',
    storageBucket: 'auth-88e83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJl1ZM1IMC9DqPxHTTyimguDRPrr0t0s',
    appId: '1:439452598995:android:d071dd16d97162e90aca26',
    messagingSenderId: '439452598995',
    projectId: 'auth-88e83',
    storageBucket: 'auth-88e83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlxjTf8pN6SRLqixZK18GfPX4LU_anKk',
    appId: '1:439452598995:ios:228608ccb9f1bd8d0aca26',
    messagingSenderId: '439452598995',
    projectId: 'auth-88e83',
    storageBucket: 'auth-88e83.appspot.com',
    iosBundleId: 'com.example.authenthication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOlxjTf8pN6SRLqixZK18GfPX4LU_anKk',
    appId: '1:439452598995:ios:228608ccb9f1bd8d0aca26',
    messagingSenderId: '439452598995',
    projectId: 'auth-88e83',
    storageBucket: 'auth-88e83.appspot.com',
    iosBundleId: 'com.example.authenthication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlWbL6rARwuMqlhF88hTGEF_UFLPrUOW8',
    appId: '1:439452598995:web:dc00a036af7211940aca26',
    messagingSenderId: '439452598995',
    projectId: 'auth-88e83',
    authDomain: 'auth-88e83.firebaseapp.com',
    storageBucket: 'auth-88e83.appspot.com',
  );

}